// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decode(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* name */Json_decode.field("name", Json_decode.string, json)
        ];
}

function present(user) {
  return $$String.concat(": ", /* :: */[
              "Here we go",
              /* :: */[
                user[/* id */0],
                /* :: */[
                  user[/* name */1],
                  /* [] */0
                ]
              ]
            ]);
}

exports.decode = decode;
exports.present = present;
/* No side effect */
