FROM node:8

RUN mkdir /app
WORKDIR /app

RUN mkdir /app/.npm-global
RUN npm config set prefix '/app/.npm-global'
ENV PATH "/app/.npm-global:${PATH}"

RUN apt-get update
RUN apt-get install -y ocaml-native-compilers

RUN npm install -g bs-platform

# COPY ./package.json ./package.json
# COPY ./bsconfig.json ./bsconfig.json
#
# RUN npm install
# RUN npm link bs-platform
#
# COPY ./src/ ./src/
#
# CMD ["npm", "run", "watch:bsb"]
