// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");
var Express = require("bs-express/src/Express.js");

var logging = Express.Middleware[/* from */5]((function (next, req) {
        var time = new Date(Date.now()).toLocaleDateString();
        console.log($$String.concat(" :: ", /* :: */[
                  time,
                  /* :: */[
                    Express.Request[/* methodRaw */13](req),
                    /* :: */[
                      Express.Request[/* path */16](req),
                      /* [] */0
                    ]
                  ]
                ]));
        return Curry._1(next, Express.Next[/* middleware */0]);
      }));

function sendHtml(text) {
  return Express.Middleware[/* from */5]((function (_, _$1) {
                var partial_arg = Express.Response[/* sendString */2];
                return (function (param) {
                    return partial_arg(text, param);
                  });
              }));
}

exports.logging = logging;
exports.sendHtml = sendHtml;
/* logging Not a pure module */
